### ISSUE TITLE
chapter 2: UDP client broadcasts go to any server

### ISSUE THREAD

**Issue by Laharah** [brandon-rhodes/fopnp#10]
While reading the book, in chapter 2 in the section about UDP broadcasts (reading the e-book, so not sure the physical page number, sorry), it says that packets sent by the udp_broadcast.py client will be picked up by any instances of the udp_broadcast servers at the same time, which they are. But the book goes on to say that normal servers won't and that I could try running a few udp_remote instances to be convinced. 

I couldn't find anything distinguishing the udp_broadcast server socket code from the udp_remote server socket code as far as socket configuration was concerned. So I tried running the udp_remote server at the same time as the udp_broadcast server and both servers received the 'Broadcast Datagram!' sent by the broadcast client. I'm not sure if the code or the book is wrong in this case, or if the situation is totally unique to my network settings somehow. 

Here's a screenshot of the broadcasts being picked up by udp_remote.py:

![udp tmux session](https://i.imgur.com/xhfxBgB.png)

So my question is, is there some socket option that's supposed to be set in the udp_broadcast server code that's supposed to make it behave differently from the udp_remote server code? Is the passage about regular servers not picking up broadcasts incorrect? Is there something about the way my network handles broadcasts that's non-standard and skewing my results?

sys info:
broadcast IP: 192.168.0.255
local: OSX 10.10.5, python 3.5, 192.168.0.175
remote: winserver 2012, cygwin, python 3.4.3, 192.168.0.125
router: tomato v1.25

**Comment by brandon-rhodes** [comment]
Since your e-book does not provide the printed page numbers, could you — so that I can find the exact sentence you are asking about — quote it verbatim for me, so that I can search my own version of the text to find the passage? Thanks!

**Comment by Laharah** [comment]
sure:

> "But when you use the local network’s broadcast address, suddenly you will see that all of the broadcast servers get the packet at the same time! (But no normal servers will see it—run a few copies of the normal udp_remote.py server while making broadcasts to be convinced.)”

**Comment by altagore** [comment]
I had the same problem. The "remote" server receives messages from the "broadcast" client.

**Comment by brandon-rhodes** [comment]
I conclude that the sentence in parenthesis is incorrect — even normal UDP servers, that have not opted-in to broadcast in any way, will see a broadcast packet if one appears on the local network. Which makes sense, and I am not sure how I could have thought otherwise? If another edition of the book is ever launched, I will make sure that the sentence gets updated!

**Comment by Laharah** [comment]
Thanks so much for clearing it up! Really enjoyed the book, very helpful.

I recently moved to Portland, so am eagerly awaiting pycon '16 :)
