### ISSUE TITLE
Python version used to compile the scripts

### ISSUE THREAD

**Issue by pelo99** [brandon-rhodes/fopnp#13]
Hey,

This is regarding your book using Python3. I happened to observe that most of the scripts you've written are being executed using the command 'python' instead of 'python3'. Assuming that you're not using an alias, 'python' on Ubuntu should point to python2 rather than python3. This would result in a wrong interpreter being used to run the scripts. Also, you're using the hashbang '#! /usr/bin/env python3' in every script and still running them using the command 'python'. I think this needs to be corrected.

**Comment by brandon-rhodes** [comment]
I agree!

**Comment by brandon-rhodes** [comment]
Oh, and, I see where the problem came from:

https://github.com/brandon-rhodes/fopnp/blob/m/py3/tools/two.sh

My code to convert the old README files to the new ones only looked for the string `python2`, not bare `python` commands!

**Comment by brandon-rhodes** [comment]
There. Let me know if you find any more instances of this issue, and thanks for letting me know!
