### ISSUE TITLE
OSError with big_sender

### ISSUE THREAD

**Issue by Telltak** [brandon-rhodes/fopnp#17]
Python3 attempting to run big_sender.py gives OSError 22 Invalid argument for line 14

**Comment by brandon-rhodes** [comment]
On my system it runs without an `OSError`:

```
$ python3 big_sender.py -p 57033 localhost
Alas, the datagram did not make it
Actual MTU: 65535
```

You might be running into a limitation of your operating system — what OS and version are you running?

**Comment by brandon-rhodes** [comment]
I am going to tentatively close this since, without data on your operating system version, I cannot pursue a fix for this — but if you do make it back to this issue later, please feel free to re-open and let me know some more details and we'll try to track down what's wrong!
