### ISSUE TITLE
Unused argument in tcp_deadlock.py

### ISSUE THREAD

**Issue by wefer** [brandon-rhodes/fopnp#19]
On line 8 `def server(host, port, bytecount):` the server takes a `bytecount` argument that appears not be used inside the procedure.

**Comment by brandon-rhodes** [comment]
Have you tried removing the argument and running the server? :)

**Comment by wefer** [comment]
I see what the problem is :) 

Maybe `def server(host, port, *args):` is better then? Since it might make it more clear that the server is unaware/indifferent of how many bytes it will receive from the client.

**Comment by brandon-rhodes** [comment]
I have made the problem go away entirely by simply calling the server and client with different arguments in the first place. I'm not sure what that didn't occur to me when you first brought up the issue! But thanks for pointing it out, and hopefully this small readability win will help a few readers from being more confused than they need to be. Thanks!

**Comment by wefer** [comment]
Thanks for a great book!
