### ISSUE TITLE
Cant launch the playground

### ISSUE THREAD

**Issue by bee80** [brandon-rhodes/fopnp#2]
hi, im using ubuntu 14.04(64) on virtualbox with win 7 64 as host, the ovm doesnt seem to work on windows so i tried to build myself on ubuntu. I get as far as ./launch and recieve these errors:

2014-12-09 06:52:06--  ftp://ftp.nl.netbsd.org/vol/2/metalab/distributions/tinycorelinux/4.x/x86/tcz/bridge-utils.tcz
           => â€˜bridge-utils.tczâ€™
Resolving ftp.nl.netbsd.org (ftp.nl.netbsd.org)... 192.87.102.42, 192.87.102.43, 2001:610:1:80aa:192:87:102:43, ...
Connecting to ftp.nl.netbsd.org (ftp.nl.netbsd.org)|192.87.102.42|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /vol/2/metalab/distributions/tinycorelinux/4.x/x86/tcz ... done.
==> SIZE bridge-utils.tcz ... 49152
==> PASV ... done.    ==> RETR bridge-utils.tcz ... done.
Length: 49152 (48K) (unauthoritative)

100%[================================================>] 49,152      --.-K/s   in 0.09s   

2014-12-09 06:52:07 (546 KB/s) - â€˜bridge-utils.tczâ€™ saved [49152]

./launch.sh: 17: ./launch.sh: tce-load: not found
Container started: h1
Container started: h2
Container started: h3
Container started: h4
Container started: modemA
Container started: modemB
Container started: isp
Container started: backbone
Container started: example
Container started: ftp
Container started: mail
Container started: www
Created interface: h1-eth1
Created interface: h2-eth1
Created interface: h3-eth1
Created interface: h4-eth1
Created interface: modemA-eth1
Created interface: modemB-eth1
Cannot find device "homeA"
Created bridge: homeA
sudo: brctl: command not found
sudo: brctl: command not found
Bridged interface: modemA-eth1
sudo: brctl: command not found
Bridged interface: h1-eth1
sudo: brctl: command not found
Bridged interface: h2-eth1
sudo: brctl: command not found
Bridged interface: h3-eth1
sudo: brctl: command not found
Cannot find device "homeB"
Created bridge: homeB
sudo: brctl: command not found
Bridged interface: modemB-eth1
sudo: brctl: command not found
Bridged interface: h4-eth1
Created interface: example-eth1
Created interface: ftp-eth0
Error: argument "mail" is wrong: Invalid "netns" value

Cannot open network namespace "mail": No such file or directory
Cannot open network namespace "mail": No such file or directory
Created interface: mail-eth0
RTNETLINK answers: File exists
Created interface: www-eth0
sudo: brctl: command not found
Cannot find device "exampleCOM"
Created bridge: exampleCOM
sudo: brctl: command not found
Bridged interface: example-eth1
sudo: brctl: command not found
Bridged interface: ftp-eth0
sudo: brctl: command not found
Bridged interface: mail-eth0
sudo: brctl: command not found
Cannot find device "www-eth0"
Bridged interface: www-eth0
Cannot find device "eth2"
Cannot find device "eth0"
Cannot find device "eth1"
Cannot find device "eth1"
Cannot find device "eth0"
Cannot find device "eth0"
RTNETLINK answers: Network is unreachable
Cannot find device "eth0"
Cannot find device "eth1"
Cannot find device "eth2"
Cannot find device "eth0"
Cannot find device "eth1"
Cannot find device "eth2"
RTNETLINK answers: Network is unreachable
Cannot find device "eth1"
Cannot find device "eth1"
RTNETLINK answers: Network is unreachable
Cannot find device "eth0"
Cannot find device "eth0"
RTNETLINK answers: Network is unreachable
Cannot find device "eth0"
Cannot find device "eth0"
RTNETLINK answers: Network is unreachable
RTNETLINK answers: Network is unreachable
Cannot open network namespace "mail": No such file or directory
Cannot open network namespace "mail": No such file or directory

please help.

**Comment by brandon-rhodes** [comment]
All right!

After months of trying to work around this problem — and after several conversations with people who have more experience with virtualization than I do — I have deprecated my original scheme of distributing a bare VirtualBox image and expecting it to run across multiple operating systems correctly, especially with network forwarding turned on.

I have just rebuilt, repackaged, and re-uploaded the Playground as a Vagrant box, because Vagrant had a reputation for doing a better job of supporting cross-platform image support than do any of the raw native back-end mechanisms for virtualization like VirtualBox.

I have amended the Playground instructions to explain starting up a Vagrant box:

https://github.com/brandon-rhodes/fopnp/tree/m/playground

Could you try out the instructions and let me know if they work on your platform and, if not, at which step they fail? Thanks so much!
