### ISSUE TITLE
docker: Error image fopnp/base:latest not found

### ISSUE THREAD

**Issue by mingsterism** [brandon-rhodes/fopnp#22]
Hi, 
I got this error after running 
`./build.sh`
`./launch.sh`

```
vagrant@vagrant-ubuntu-trusty-64:~/fopnp/playground$ ./launch.sh
++ dirname ./launch.sh
+ cd .
+ grep -q docker
++ groups
+ echo 'vagrant docker'
+ '[' '!' -x /sbin/brctl ']'
+ sudo mkdir -p /var/run/netns
+ sudo modprobe ip_nat_ftp nf_conntrack_ftp
+ start_container h1 fopnp/base 2201
+ hostname=h1
+ image=fopnp/base
+ port=2201
+ container=h1
++ docker inspect -f '{{.State.Pid}}' h1
++ true
+ pid=
+ '[' '' = '' ']'
+ '[' -n 2201 ']'
+ netopts=--publish=2201:22
++ readlink -f ..
+ docker run --name=h1 --hostname=h1 --dns=10.1.1.1 --dns-search=example.com --publish=2201:22 --volume=/home/vagrant/fopnp:/fopnp -d fopnp/base
Unable to find image 'fopnp/base:latest' locally
Pulling repository docker.io/fopnp/base
docker: Error: image fopnp/base:latest not found.
See 'docker run --help'.

```

appreciate any help  
Thanks

**Comment by mingsterism** [comment]
I got it working already :)

**Comment by brandon-rhodes** [comment]
Wonderful! Feel free to leave a comment with what the issue was, in case anyone else runs into this error message and can't guess how to get past it.

**Comment by AllanRPereira** [comment]
How did you solve it?
I have the same problem

**Comment by prinwis** [comment]
@AllanRPereira I meet the same problem too. My solution is remove the vm image in virtualbox and reinstall (vagrant up again), and it behave normal. But I don't know why. I use a proxy to download the docker file, so maybe it is related to the proxy, cancel your proxy setttings before you reoperate. I hope it works for you.
