### ISSUE TITLE
IN means？

### ISSUE THREAD

**Issue by chashisu** [brandon-rhodes/fopnp#26]
Is IN is a module?

**Comment by brandon-rhodes** [comment]
Yes! “IN” containers the "Internet" symbols under Python 2 or Python 3.

**Comment by lucifer-v** [comment]
Help, I use python3.6.1, but when I import IN module, it ocurrs " No module named 'IN' "

**Comment by brandon-rhodes** [comment]
Alas, it looks like they removed it from Python 3.6!

https://twitter.com/grelleum/status/893140086153502725

I wonder if I should just copy the value into the source from my system file:

`/usr/src/linux-headers-4.10.0-28/include/uapi/linux/in.h`

There's nowhere else to get this value, like `/proc` or `/sys`, is there?
