### ISSUE TITLE
Chapter 06: lib.SSL_get_version segfaults on python3.6.6 darwin 16.7.0

### ISSUE THREAD

**Issue by zhammer** [brandon-rhodes/fopnp#30]
I'm getting a segfault on my mac osx on the following line: https://github.com/brandon-rhodes/fopnp/blob/2c1d0fcb97560394d0fa52eead317567b1f02504/py3/chapter06/test_tls.py#L81.

### `SSL_get_version` with debug prints
```py
def SSL_get_version(ssl_sock):
    """Reach behind the scenes for a socket's TLS protocol version."""

    print('\n--START SSL_get_version--\n')

    lib = ctypes.CDLL(ssl._ssl.__file__)
    print('lib:', lib)

    lib.SSL_get_version.restype = ctypes.c_char_p
    print('lib.SSL_get_version.restype:', lib.SSL_get_version.restype)

    address = id(ssl_sock._sslobj)
    print('address:', address)

    struct = ctypes.cast(address, ctypes.POINTER(PySSLSocket)).contents
    print('struct:', struct)

    version_bytestring = lib.SSL_get_version(struct.ssl)
    print('doesnt get here')

    return version_bytestring.decode('ascii')
```
### `test_tls.py` output:
```
Zachs-MBP:chapter06 zhammer$ ./test_tls.py localhost 1060 -a ca.crt

Address we want to talk to.......... ('localhost', 1060)
Peer certificate.................... provided
Name(s) on peer certificate......... localhost
Whether name(s) match the hostname.. Yes
Certificates loaded of type crl..... 0
Certificates loaded of type x509.... 1
Certificates loaded of type x509_ca. 0

--START SSL_get_version--

lib: <CDLL '/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload/_ssl.cpython-36m-darwin.so', handle 7faf3c522df0 at 0x10cc14320>
lib.SSL_get_version.restype: <class 'ctypes.c_char_p'>
address: 4508905200
struct: <__main__.PySSLSocket object at 0x10cc11378>
Segmentation fault: 11
```

### System info:
```
Zachs-MBP:chapter06 zhammer$ python3 --version
Python 3.6.6
Zachs-MBP:chapter06 zhammer$ uname -a
Darwin Zachs-MBP.fios-router.home 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
```

### Notes
I'm not familiar with ctypes or the ssl library, so I wasn't able to do much debugging on my end. Let me know what I can do to provide more info.

**Comment by brandon-rhodes** [comment]
Thanks for the report! I'm not sure how soon I'll get the chance to dig in and debug this, but the big question will be whether this depends on the operating system (Mac vs Linux) or whether the struct underlying Python 3.6 is different and my ctypes code — which hand-copies the shape of the C language struct as I read it out of the SSL `.h` file in the Python source code — needs to be updated and be different for different versions of Python.

If you're interested in debugging yourself, simply dig into the older `.h` files that define the SSL struct, looking for the same fields you can see me naming in my ctypes code. Chances are that the fields changed somewhere between earlier versions of Python 3 and the version Python 3.6 that you're using, and that my module needs an `if` statement to select a new list of fields if the Python version is recent enough. Feel free to comment here with further findings as you explore!

**Comment by dellnoantechnp** [comment]
### SSLSocket.version()
Return the actual SSL protocol version negotiated by the connection as a string, or None is no secure connection is established. As of this writing, possible return values include "SSLv2", "SSLv3", "TLSv1", "TLSv1.1" and "TLSv1.2". Recent OpenSSL versions may define more return values.

New in version 3.5.


---
        if sys.version_info >= (3, 5):
            protocol_version = ssl_sock.version()
        else:
            protocol_version = SSL_get_version(ssl_sock)

**Comment by brandon-rhodes** [comment]
Oh, neat! The next time I return to these fopnp examples to update them, I'll include this fix.
