### ISSUE TITLE
Chapter 1 examples no longer work

### ISSUE THREAD

**Issue by jauerb** [brandon-rhodes/fopnp#31]
The examples in Chapter 1 no longer work, because 

(a) The Google Geocoder API  now requires an API key, and (b) it now requires all requests to be made over https

I have made a fix in my fork of the repo (For Python 3 at least) that will work as soon as a valid API key is placed in a text file in the same directory.  Please, let me know if you would like me to make a pull request.

**Comment by brandon-rhodes** [comment]
Thanks for letting me know! I'd prefer to point users at a different service that doesn't provide API keys. When I get the chance, I'll search to see if there are any geolocation services that don't require one yet.

**Comment by brandon-rhodes** [comment]
Thanks again for pointing out that these scripts were broken. I've rewritten them (well, the Python 3 examples; I'll leave it to another contributor, maybe at a conference sprint sometime if not before, to translate them to Python 2) to use the Open Street Maps project — let me know if you have any trouble now that they're pointed at another service!

**Comment by jauerb** [comment]
This seems to be working for me now.  Just required pip installing geopy (and requests, for search2.py, which was already needed in the old examples).

Thanks for updating!
