### ISSUE TITLE
To recieve data contiuously from tcp barcode scanners

### ISSUE THREAD

**Issue by Thyagutamizhan** [brandon-rhodes/fopnp#32]
HI there, Actually im a beginner for python. I wanna recieve data contiuously from multiple  tcp connected barcode scanners.

**Comment by brandon-rhodes** [comment]
Alas, the book does not cover barcode protocols specifically, so none of the examples here from the printed book illustrate those protocols — have you tried doing a Google search to see if anyone has sample code up? What is the protocol called?

**Comment by brandon-rhodes** [comment]
I'm going to close this issue pending further information about the protocol used by the barcode scanners, but feel free to re-open once you have more information!
