### ISSUE TITLE
chapter 08 memcache not working

### ISSUE THREAD

**Issue by konjecturer0** [brandon-rhodes/fopnp#35]
Running chapter08/squares.py just hangs up. It looks like the library memcache is not working like before.

`#!/usr/bin/env python3
# Foundations of Python Network Programming, Third Edition
# https://github.com/brandon-rhodes/fopnp/blob/m/py3/chapter08/squares.py
# Using memcached to cache expensive results.

import memcache, random, time, timeit

def compute_square(mc, n):
    value = mc.get('sq:%d' % n)
    if value is None:
        time.sleep(0.001)  # pretend that computing a square is expensive
        value = n * n
        mc.set('sq:%d' % n, value)
    return value

def main():
    mc = memcache.Client(['127.0.0.1:11211'])

    def make_request():
        compute_square(mc, random.randint(0, 5000))

    print('Ten successive runs:')
    for i in range(1, 11):
        print(' %.2fs' % timeit.timeit(make_request, number=2000), end='')
    print()

if __name__ == '__main__':
    main()`

**Comment by brandon-rhodes** [comment]
Can you connect to your memcache instance with other tools, like `telnet 127.0.0.1 11211`?

**Comment by konjecturer0** [comment]
I'm unable to telnet. But after running the script again and waiting some time the following result pops up:
`Ten successive runs:
 3.97s 3.97s 3.97s 3.94s 3.95s 3.94s 3.96s 3.94s 3.96s 3.91s`

Which looks to be by far much different than that of the book.
Furthermore when creating a memcache instance (using python 3.7.5) a result different from the book also seems to prompt:
`>> import memcache`
`>> mc = memcache.Client(['127.0.0.1:11211])`
`>> mc.set('test', 1)
      0`
`>> mc.get('test')
      [nothing actually happens]`

**Comment by brandon-rhodes** [comment]
I recommend first working purely with memcache and telnet until you have a reliable connection you can set up by hand. Only then, when I knew memcache was working well, would I turn my attention to trying to talk to memcache with a scripting language like Python.

**Comment by brandon-rhodes** [comment]
@vladic4t I wanted to check back now that it’s February! Did you make progress on determining why you were not able to connect to the memcache instance you had installed?

**Comment by brandon-rhodes** [comment]
Pending more information about your experiment with memcache, I'm going to close this for now, but please feel free to comment further if you have more questions!
