### ISSUE TITLE
SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

### ISSUE THREAD

**Issue by hhsecond** [brandon-rhodes/fopnp#9]
Hi Rhodes,

It's been a privilege to use your product and study stuffs from there. Unfortunately I've come across to an error but could not find any easy solution from google. I am using ubuntu 14.04 Lts and virtualbox 5.x

I've executed "vagrant up --provider virtualbox" command and was waiting for it to complete. Then after around 80% I got this error.

 default: URL: https://atlas.hashicorp.com/brandon-rhodes/playground
==> default: Adding box 'brandon-rhodes/playground' (v1.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/brandon-rhodes/boxes/playground/versions/1.0/providers/virtualbox.box

An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Could you please have a look into this issue

**Comment by brandon-rhodes** [comment]
Alas! As I do not run the Hashicorp servers, I have no way to know why your connection might be failing. Is it difficult for you to perform very large downloads from anywhere else? Or is Hashicorp the only company from which downloads sometimes get cancelled?

**Comment by brandon-rhodes** [comment]
I am going to close this temporarily until we can collect more information about the failure you encountered. If you learn more information and can post it here in a comment, please do so, and we'll work to get it resolved!

**Comment by a-eid** [comment]
I am experiencing the same problem? 

```bash 


Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'kenyiu/ubuntu-nginx-php7' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'kenyiu/ubuntu-nginx-php7'
    default: URL: https://atlas.hashicorp.com/kenyiu/ubuntu-nginx-php7
==> default: Adding box 'kenyiu/ubuntu-nginx-php7' (v0.0.1) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/kenyiu/boxes/ubuntu-nginx-php7/versions/0.0.1/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
    default: Progress: 38% (Rate: 0/s, Estimated time remaining: 0:25:01)
    default: Progress: 38% (Rate: 0/s, Estimated time remaining: 0:25:03)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
```
